### ISSUE TITLE
Warning when compiling release/circ2024

### ISSUE THREAD

**Issue by Pmichaud29** [robotique-udes/rover#10]
Quand on compile rover_gui, ce warning apparait:

stderr: rover_gui                                             
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
  
 À investiguer pls

**Comment by Ndumoulin** [comment]
C'est un problème qui vient de ROS2 directement j'avais ce warning au debut, il faut downgrade le "setuptools" package à la version 52.8.0 avec "pip install setuptools==58.2.0" je vais le rajouter à la doc.

https://answers.ros.org/question/396439/setuptoolsdeprecationwarning-setuppy-install-is-deprecated-use-build-and-pip-and-other-standards-based-tools/

**Comment by Pmichaud29** [comment]
Good thanks! Une fois que ça sera rajouté à la doc et merge dans release tu closeras l'issue
